image:
  name: docker/compose:1.29.2
  entrypoint:
    - ""

services:
  - docker:dind

stages:
  - test
  - publish
  - deploy

test:
  stage: test
  script:
    - make test || exit 1
  # when: manual

publish:
  stage: publish
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - make publish

deploy:
  stage: deploy
  # only:
  #   - master
  script:
    - echo
    - NEW_VERSION=$(grep -o '^[a-z_0-9]\+\.[0-9]\+\.[0-9_a-z]\+' CHANGES.log | head -n1)
    - ssh -i ~/keys/notifier_rsa nic@notifier.nic-weiss.tech -p 2222 " bash -c \"
      echo '------OPEN PROJECT AND STOP------' &&
      cd $PROJECT_PATH &&
      git stash &&
      [[ -f 'docker/docker-compose-production.yml' ]] && make down_production || echo skip &&

      echo '------GET MASTER VERSION $NEW_VERSION------' &&
      git pull &&
      git checkout tags/$NEW_VERSION &&
      git pull &&

      echo '------LOGIN DOCKERHUB------' &&
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&

      echo '------MIGRATE------' &&
      make migrate_prod &&
      make down_production &&
      docker rm -f notifier_mysql-production

      echo '------REMOVE LOCKS------' &&
      cd api/tmp/lock/ &&
      rm -rf ./* &&
      cd ../../../ &&

      echo '------UP NEW------' &&
      make prod_ps &&
      make production &&

      echo '------DONE------' &&
      ./notify_about_release.sh $CHAT_ID $TOKEN \""
  when: manual
