image:
  name: docker/compose:1.29.2
  entrypoint:
    - ""

services:
  - docker:dind

stages:
  - test
  - publish
  - deploy

test:
  stage: test
  script:
    - make test
  when: manual

publish:
  stage: publish
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make publish

deploy:
  stage: deploy
  # only:
  #   - master
  script:
    - echo
    - ssh -i ~/keys/notifier_rsa nic@notifier.nic-weiss.tech -p 2222 "
      cd $PROJECT_PATH &&
      git stash &&
      docker-compose -f docker/docker-compose-production.yml down &&
      git pull &&
      git checkout feature/version_3 &&
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      make production &&
      make migrate_prod &&
      ./notify_about_release.sh $CHAT_ID $TOKEN"
  when: manual
