"""Field changes

Revision ID: 25482c9a6625
Revises: 09c320426749
Create Date: 2023-03-27 19:30:18.009620+00:00

"""
from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25482c9a6625'
down_revision = '09c320426749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'client')
    op.add_column('session', sa.Column('client', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'client')
    op.add_column('session', sa.Column('client', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
