"""Add repeate interval for notify

Revision ID: 6b5b147bcb66
Revises: 52eab21aedaa
Create Date: 2023-05-13 10:49:01.051087+00:00

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '6b5b147bcb66'
down_revision = '52eab21aedaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notify', sa.Column('repeate_interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notify', 'repeate_interval')
    # ### end Alembic commands ###
