"""Update fields for date operations

Revision ID: 52eab21aedaa
Revises: 4709d0bf479c
Create Date: 2023-04-02 18:23:11.923870+00:00

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '52eab21aedaa'
down_revision = '4709d0bf479c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date_operation', sa.Column('status', sa.Unicode(), nullable=True))
    op.drop_column('date_operation', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date_operation', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('date_operation', 'status')
    # ### end Alembic commands ###
