"""default systems

Revision ID: db7b38765f04
Revises: d1e30855741d
Create Date: 2023-04-01 18:33:22.364779+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7b38765f04'
down_revision = 'd1e30855741d'
branch_labels = None
depends_on = None


def upgrade():
    sql = '''
    INSERT INTO system (id, name, is_disabled, is_system, help, type, is_deleted) VALUES
    (100, 'Telegram', false, false, ' Нужен id: <br>Для этого откройте бота <a target="_blank" href="http://t.me/my_id_bot">What is my ID</a>, зaпустите его. Cкопируйте код. <br><span style="color: #e05959;"><br>Внимание, для получения оповещений необходимо подписаться на бота</span> <a target="_blank" href="http://t.me/WeissNotifierSystem_bot"> Notifier</a>', 'tg', false);

   INSERT INTO system (id, name, is_disabled, is_system, help, type, is_deleted) VALUES
    (101, 'Email', false, false, 'Укажите адрес электронной почты', 'email', false);

     INSERT INTO system (id, name, is_disabled, is_system, help, type, is_deleted) VALUES
    (102, 'Push', false, true, '', 'push', false);
    '''

    op.execute(sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
