"""Add notify autodisable

Revision ID: 77c7989a9a0d
Revises: 6b5b147bcb66
Create Date: 2023-05-13 17:17:18.646609+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app


# revision identifiers, used by Alembic.
revision = '77c7989a9a0d'
down_revision = '6b5b147bcb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notify', sa.Column('is_autodisable', sa.Boolean(), nullable=True))
    op.add_column('notify', sa.Column('autodisable_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notify', 'autodisable_at')
    op.drop_column('notify', 'is_autodisable')
    # ### end Alembic commands ###
