"""Update fields for date operations

Revision ID: 88b3ad9b785e
Revises: db7b38765f04
Create Date: 2023-04-02 17:31:33.360099+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app


# revision identifiers, used by Alembic.
revision = '88b3ad9b785e'
down_revision = 'db7b38765f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date_operation', sa.Column('create_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('date_operation', sa.Column('complete_at', nullable=True))
    op.drop_column('date_operation', 'complete_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date_operation', sa.Column('complete_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('date_operation', 'complete_at')
    op.drop_column('date_operation', 'create_at')
    # ### end Alembic commands ###
