"""Process time for date operations

Revision ID: 02672b755ca5
Revises: 77c7989a9a0d
Create Date: 2023-05-14 14:10:54.489821+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app


# revision identifiers, used by Alembic.
revision = '02672b755ca5'
down_revision = '77c7989a9a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date_operation', sa.Column('start_process_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('date_operation', 'start_process_at')
    # ### end Alembic commands ###
