"""Field changes

Revision ID: d1e30855741d
Revises: 0eb9fcdb09a0
Create Date: 2023-03-29 22:44:57.972326+00:00

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'd1e30855741d'
down_revision = '0eb9fcdb09a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notify_acceptor', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notify_acceptor', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
