"""Field changes

Revision ID: 0eb9fcdb09a0
Revises: 25482c9a6625
Create Date: 2023-03-27 21:31:24.622519+00:00

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '0eb9fcdb09a0'
down_revision = '25482c9a6625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
