"""Update location field

Revision ID: a28090e372c1
Revises: 02672b755ca5
Create Date: 2023-05-14 17:27:15.149601+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a28090e372c1'
down_revision = '02672b755ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'location')
    op.add_column('session', sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    sql = '''
    ALTER TABLE public."session" ALTER COLUMN "location" TYPE json USING "location"::json;
    '''

    op.execute(sql)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'location')
    op.add_column('session', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
