"""Field changes

Revision ID: 09c320426749
Revises: 2b1b414a98da
Create Date: 2023-03-27 19:09:17.928158+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '09c320426749'
down_revision = '2b1b414a98da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'client',
                    existing_type=sa.JSON(),
                    nullable=True)
    op.add_column('user', sa.Column('registred_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registred_at')
    # ### end Alembic commands ###
