version: "3"
services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "56101:3306"
    volumes:
      - ./mysql:/mysql
    container_name: notifier_mysql

  php-fpm:
    build:
      context: ./php-fpm
    ports:
      - "56105:9000"
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ../api:/var/www
    container_name: notifier_php_fpm

  php-cli:
    build:
      context: ./php-cli
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ../api:/var/www
    container_name: notifier_php_cli

  backend:
    image: nginx:latest
    ports:
      - "56102:80"
      - "56103:443"
    volumes:
      - ./backend/:/etc/nginx/conf.d
      - ../api:/var/www
    links:
        - php-fpm
    container_name: notifier_backend

  frontend:
    build:
      dockerfile: ../docker/frontend/Dockerfile
      context: ../frontend
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/frontend
      - ./frontend/:/etc/nginx/conf.d
    depends_on:
      - backend
    working_dir: /frontend
    command: ember s
    container_name: notifier_frontend

  cron:
    build:
      context: ./cron
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./cron:/cron
      - ../api:/var/www
    container_name: notifier_cron
