version: "3.6"
services:

  ingress:
    build:
      dockerfile: docker/ingress/Dockerfile
      context: ../
      target: dev
    ports:
      - "8088:80"
    depends_on:
      - mysql
      - frontend
      - backend
    links:
      - backend
      - frontend
    container_name: dev_notifier_ingress

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: notifier
    volumes:
      - ../data/mysql:/var/lib/mysql
    container_name: dev_notifier_mysql

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '8095:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redispass#123
    volumes:
      - ../data/redis:/data
    container_name: dev_notifier_redis

  backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: ../
    env_file:
      - ../api/config/config.env
    ports:
      - "8092:9000"
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ../api:/var/www
      - ./backend/grafana.yml:/etc/agent/agent.yaml
    command: bash /start.sh
    container_name: dev_notifier_backend

  frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: ../
      target: dev
    ports:
      - "8093:4200"
    volumes:
      - ../frontend/app:/frontend/app
      - ../frontend/config:/frontend/config
      - ../frontend/public:/frontend/public
      - ../frontend/vendor:/frontend/vendor
      - ../frontend/.ember-cli:/frontend/.ember-cli
      - ../frontend/app.json:/frontend/app.json
      - ../frontend/ember-cli-build.js:/frontend/ember-cli-build.js
      - ../frontend/package.json:/frontend/package.json
    depends_on:
      - backend
    working_dir: /frontend
    command: ember s
    container_name: dev_notifier_frontend
