version: "3.6"


x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '1m'
    max-file: '1'


services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "8096:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: notifier
    volumes:
      - ../data/mysql:/var/lib/mysql
    container_name: dev_notifier_mysql

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - "8097:5432"
    container_name: dev_notifier_postgres

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '8095:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redispass#123
    volumes:
      - ../data/redis:/data
    container_name: dev_notifier_redis

  backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: ../
    env_file:
      - ../api/config/config.env
    ports:
      - "8094:80"
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ../api:/var/www
      - ./backend/grafana.yml:/etc/agent/agent.yaml
    command: bash /start.sh
    container_name: dev_notifier_backend

  frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: ../
      target: dev
    ports:
      - "8093:4200"
    volumes:
      - ../frontend/app:/frontend/app
      - ../frontend/config:/frontend/config
      - ../frontend/public:/frontend/public
      - ../frontend/vendor:/frontend/vendor
      - ../frontend/.ember-cli:/frontend/.ember-cli
      - ../frontend/app.json:/frontend/app.json
      - ../frontend/ember-cli-build.js:/frontend/ember-cli-build.js
      - ../frontend/package.json:/frontend/package.json
    depends_on:
      - backend
    working_dir: /frontend
    command: ember s
    container_name: dev_notifier_frontend

  postfix:
    build:
      dockerfile: ./docker/postfix/Dockerfile
      context: ../
    ports:
      - "25:25"
      - "587:587"
    restart: always
    command: bash -c "/run.sh"
    container_name: dev_notifier_postfix
    stdin_open: true
    tty: true
    logging: *default-logging
