definitions:
  api_utils.ErrorData:
    properties:
      code:
        type: string
      description:
        type: string
    type: object
  api_utils.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/api_utils.ErrorData'
      status:
        type: string
    type: object
  schemas.LoginParams:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  schemas.SessionResponse:
    properties:
      session:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      description: Login, create new session, return auth cookies
      parameters:
      - description: Login credentials
        in: body
        name: payload
        schema:
          $ref: '#/definitions/schemas.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: Session token
          schema:
            $ref: '#/definitions/schemas.SessionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api_utils.ErrorResponse'
      summary: Login in system
      tags:
      - Auth
swagger: "2.0"
