"""user

Revision ID: a64644047135
Revises: 3c6ed94c2825
Create Date: 2023-03-23 21:42:01.048252+00:00

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'a64644047135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Unicode(), nullable=True),
                    sa.Column('email', sa.Unicode(), nullable=True),
                    sa.Column('password', sa.Unicode(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('user_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_model_pkey')
                    )
    op.drop_table('user')
    # ### end Alembic commands ###
